#!/bin/sh
set -e
# chromium-browser \
# && --headless --no-sandbox --disable-gpu  \
# && --remote-debugging-address=0.0.0.0 \
# && --remote-debugging-port=9222 \
# && --disable-dev-shm-usage \
# && --window-size=1920,1080 \
# # Disable various background network services, including extension updating,
# #   safe browsing service, upgrade detector, translate, UMA
# && --disable-background-networking \
# # Disable installation of default apps on first run
# && --disable-default-apps \
# # Disable all chrome extensions entirely
# && --disable-extensions \
# # Disable syncing to a Google account
# && --disable-sync \
# # Disable chrome pop-up notifications which cover the page
# && --disable-notifications \
# # Disable built-in Google Translate service
# && --disable-translate \
# # Hide scrollbars on generated images/PDFs
# && --hide-scrollbars \
# # Disable reporting to UMA, but allows for collection
# && --metrics-recording-only \
# # Mute audio
# && --mute-audio \
# # Skip first run wizards
# && --no-first-run \
# # Disable fetching safebrowsing lists, likely redundant due to disable-background-networking
# && --safebrowsing-disable-auto-update \
# # set user data path
# && --user-data-dir=/data/chrome \
#exec chromedriver --whitelisted-ips=192.168.239.129,127.0.0.1 --verbose --log-path=/tmp/chromedriver.log $@

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- chromedriver "$@"
fi

exec "$@"
